training:
  epochs: 200
  loss_type: mean_flow
  batch_size: 256
  learning_rate: 0.00001
  warmup_epochs: 0
  min_lr: 0.00001

model:
  type: dit
  hidden_dim: 128
  num_heads: 4
  num_layers: 8
  patch_size: 4
  dataset: mnist
  in_channels: 1
  c: 1
  w: 28
  h: 28
  image_size: 28
  w_min: 1.0
  w_max: 5.0
  p_uncond: 0.1
  num_classes: 10