training:
  epochs: 30
  loss_type: mean_flow
  batch_size: 128
  learning_rate: 0.0001
  min_lr: 0.0001
  warmup_epochs: 0

model:
  type: unet
  down_in_1: 1
  down_out_1: 32
  down_in_2: 32
  down_out_2: 64
  prefinal: 16
  time_in: 128
  time_out: 256