training:
  epochs: 100
  batch_size: 128
  learning_rate: 0.001
  warmup_epochs: 5
  min_lr: 0.00001

model:
  type: unet
  down_in_1: 1
  down_out_1: 64
  down_in_2: 64
  down_out_2: 256
  prefinal: 32
  time_in: 128
  time_out: 256